"""kappa_packer.py — pack older append-only JSONL shards into Parquet.

Generalized from `experiments/jepa_structured_data/storage_packer.py`.
Same pattern: a directory contains time-sharded `*.jsonl` files (one
record per line, append-only). Files older than `--age-hours` get
read in, written as zstd-compressed Parquet, and the source JSONL
deleted. Idempotent — re-running with the same args is a no-op.

This is the canonical Kappa-architecture move:
    JSONL = the append-only log (cheap to write, schema-flexible)
    Parquet = the materialized columnar view (cheap to read, query)

Reader contract (transparent fallback): consumers should look for
`<base>.parquet` first, then `<base>.jsonl`. Either is the source of
truth depending on whether the shard has been packed yet.

Time-sharded naming convention:
    <stream>-<YYYY-MM-DD>.jsonl       active or recent shard
    <stream>-<YYYY-MM-DD>.parquet     packed shard (zstd)
where <stream> is "metrics" / "samples" / "events" / etc.

Usage:
    # Show what would be packed
    python kappa_packer.py --dir checkpoints/lm/streams --dry-run

    # Pack everything older than 24 hours
    python kappa_packer.py --dir checkpoints/lm/streams --age-hours 24

    # Pack everything regardless of age (e.g. final flush at end of run)
    python kappa_packer.py --dir checkpoints/lm/streams --age-hours 0

    # Recursive — walk subdirectories
    python kappa_packer.py --dir checkpoints/ --recursive

After packing, CloudArchive's next sync will push the Parquet shards
to the HF bucket + local mirror. The deleted JSONL won't reappear on
the remote because sync_bucket compares names: parquet-only on remote
is the desired end state.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path


def _pa():
    """Lazy pyarrow import so the rest of the module works when not packing."""
    import pyarrow as pa
    import pyarrow.parquet as pq
    return pa, pq


def read_records(path: Path) -> list[dict]:
    """Read a stream record-by-record from .parquet (preferred) or .jsonl."""
    parquet = path.with_suffix(".parquet")
    if parquet.exists():
        _, pq = _pa()
        return pq.read_table(parquet).to_pylist()
    if path.exists() and path.suffix == ".jsonl":
        out = []
        with path.open("r", encoding="utf-8", errors="replace") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    out.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
        return out
    return []


def pack_one(jsonl_path: Path, *, delete_source: bool = True) -> dict:
    """JSONL → zstd Parquet. Returns a small report dict."""
    if not jsonl_path.exists() or jsonl_path.suffix != ".jsonl":
        return {"skipped": "not a jsonl file", "path": str(jsonl_path)}
    parquet_path = jsonl_path.with_suffix(".parquet")
    if parquet_path.exists():
        # Already packed (possibly partially). Re-pack into a temp file
        # then rename, so we never leave a torn .parquet behind.
        pass

    pa, pq = _pa()
    records = []
    with jsonl_path.open("r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    if not records:
        return {"skipped": "empty", "path": str(jsonl_path)}

    # Coerce nested dict / list fields to JSON strings so the schema is
    # uniform across rows (the storage_packer pattern).
    for r in records:
        for k, v in list(r.items()):
            if isinstance(v, (dict, list)) and k != "_meta":
                # leave _meta as-is (already string-coerced by old code if
                # generated by storage_packer); for arbitrary nested fields
                # stringify only if heterogeneous types appear in column.
                pass
        if "_meta" in r and not isinstance(r["_meta"], str):
            r["_meta"] = json.dumps(r["_meta"])

    table = pa.Table.from_pylist(records)
    tmp = parquet_path.with_suffix(".parquet.tmp")
    pq.write_table(table, tmp, compression="zstd")
    tmp.replace(parquet_path)

    bytes_before = jsonl_path.stat().st_size
    bytes_after = parquet_path.stat().st_size
    if delete_source:
        jsonl_path.unlink()

    return {
        "path": str(jsonl_path),
        "n_records": len(records),
        "bytes_before": bytes_before,
        "bytes_after": bytes_after,
        "ratio": round(bytes_after / max(1, bytes_before), 3),
    }


def find_jsonl_shards(root: Path, recursive: bool = False) -> list[Path]:
    if recursive:
        return sorted(p for p in root.rglob("*.jsonl") if p.is_file())
    return sorted(p for p in root.glob("*.jsonl") if p.is_file())


def is_old_enough(path: Path, age_hours: float) -> bool:
    if age_hours <= 0:
        return True
    age_s = time.time() - path.stat().st_mtime
    return age_s >= age_hours * 3600.0


def cmd_pack(args: argparse.Namespace) -> None:
    root = Path(args.dir)
    if not root.is_dir():
        print(f"not a directory: {root}", file=sys.stderr)
        sys.exit(2)

    shards = find_jsonl_shards(root, recursive=args.recursive)
    eligible = [p for p in shards if is_old_enough(p, args.age_hours)]

    if args.dry_run:
        print(f"dry-run: {len(eligible)}/{len(shards)} JSONL shards would be packed")
        for p in eligible:
            mtime_age_h = (time.time() - p.stat().st_mtime) / 3600
            print(f"  {p}  ({p.stat().st_size:,} bytes, age={mtime_age_h:.1f}h)")
        return

    if not eligible:
        print(f"nothing to pack ({len(shards)} JSONL files in {root}, "
              f"none older than {args.age_hours}h)")
        return

    total_before = total_after = 0
    print(f"packing {len(eligible)} JSONL shard(s) in {root}:")
    for p in eligible:
        r = pack_one(p, delete_source=not args.keep_jsonl)
        if r.get("skipped"):
            print(f"  - {p.name}: skipped ({r['skipped']})")
            continue
        print(f"  + {p.name}: {r['n_records']:,} rows, "
              f"{r['bytes_before']:,} → {r['bytes_after']:,} bytes "
              f"(ratio {r['ratio']:.3f})")
        total_before += r["bytes_before"]
        total_after += r["bytes_after"]

    if total_before:
        print(f"\ntotal: {total_before:,} → {total_after:,} bytes "
              f"({100 * total_after / total_before:.1f}%)")


def cmd_status(args: argparse.Namespace) -> None:
    root = Path(args.dir)
    if not root.is_dir():
        print(f"not a directory: {root}", file=sys.stderr)
        sys.exit(2)
    n_jsonl = sum(1 for p in find_jsonl_shards(root, args.recursive))
    n_parquet = len(list(
        root.rglob("*.parquet") if args.recursive else root.glob("*.parquet")
    ))
    j_bytes = sum(
        p.stat().st_size for p in find_jsonl_shards(root, args.recursive)
    )
    p_bytes = sum(
        p.stat().st_size
        for p in (root.rglob("*.parquet") if args.recursive else root.glob("*.parquet"))
    )
    print(f"directory:    {root}")
    print(f"  JSONL:      {n_jsonl} files, {j_bytes:,} bytes "
          f"({j_bytes / 1024 / 1024:.2f} MB)")
    print(f"  Parquet:    {n_parquet} files, {p_bytes:,} bytes "
          f"({p_bytes / 1024 / 1024:.2f} MB)")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--dir", default="data/streams",
                    help="directory containing JSONL shards")
    ap.add_argument("--age-hours", type=float, default=24.0,
                    help="only pack shards whose mtime is older than this "
                         "(default 24h; 0 = pack all)")
    ap.add_argument("--recursive", action="store_true",
                    help="walk subdirectories")
    ap.add_argument("--keep-jsonl", action="store_true",
                    help="don't delete the source JSONL after packing")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--status", action="store_true",
                    help="show JSONL/Parquet counts and exit")
    args = ap.parse_args()

    if args.status:
        cmd_status(args)
    else:
        cmd_pack(args)


if __name__ == "__main__":
    main()
