"""step_decode — O(1)-per-token autoregressive decoder using
Mamba3Block.step / ProgressiveModel.forward_step.

The naive decoder in length_gen_*.py reruns the full prefix at every
step, costing O(L^2) per query. For F(20)=6765 ones that becomes
unworkable. The step decoder caches the SSM hidden state per layer
and processes only the new token each step — O(L) per query.

Bit-equivalent to running the full forward pass and reading argmax
at every position (verified at sequence-level by `test_step_parity`).
"""
import sys
sys.path.insert(0, ".")
import torch

EOS = 257
SEP_TOKEN = 258
BOS_TOKEN = 256


def _build_counter_array(sep_pos, current_len, n_counter, sentinel,
                         max_count=None):
    """The counter array for the entire current prefix."""
    cv = [sentinel] * current_len
    for k in range(n_counter + 1):
        p = sep_pos + k
        if 0 <= p < current_len:
            v = max(0, n_counter - k)
            if max_count is not None:
                v = min(v, max_count)
            cv[p] = v
    return cv


def step_decode(model, prefix_tokens, sep_pos, n_counter,
                max_steps, device, max_count=None):
    """Step-mode autoregressive decode.

    prefix_tokens: list[int] — tokens up to and including SEP
    sep_pos:       index of SEP in prefix_tokens
    n_counter:     int — counter value at SEP (oracle-supplied)

    Returns the list of generated bytes (excluding EOS).
    """
    sentinel = (max_count + 1) if max_count is not None else (
        model.loop_counter.sentinel if model.loop_counter is not None else 0)

    # Prime the SSM state by stepping through the prefix one token at a time.
    states = model.init_decode_state(batch_size=1)
    out = []
    cur_len = 0
    for tok_id in prefix_tokens:
        cur_len += 1
        cv_full = _build_counter_array(sep_pos, cur_len, n_counter,
                                        sentinel, max_count)
        c_t = torch.tensor([[cv_full[-1]]], dtype=torch.long, device=device)
        t = torch.tensor([[tok_id]], dtype=torch.long, device=device)
        with torch.no_grad():
            logits, states = model.forward_step(t, counter_value=c_t, states=states)
    # The logits at the SEP position predict the first answer byte.
    # Its argmax is the first generated token.
    next_tok = int(logits[0, -1].argmax().item())

    for step in range(max_steps):
        if next_tok == EOS:
            break
        out.append(next_tok)
        cur_len += 1
        cv_full = _build_counter_array(sep_pos, cur_len, n_counter,
                                        sentinel, max_count)
        c_t = torch.tensor([[cv_full[-1]]], dtype=torch.long, device=device)
        t = torch.tensor([[next_tok]], dtype=torch.long, device=device)
        with torch.no_grad():
            logits, states = model.forward_step(t, counter_value=c_t, states=states)
        next_tok = int(logits[0, -1].argmax().item())

    return out


def test_step_parity(model, sample_n_counter, prefix_text, device, max_count=None):
    """Sanity check: step decode produces same bytes as full forward."""
    from progressive_model import ByteTokenizer
    tok = ByteTokenizer()
    inp_bytes = list(prefix_text.encode("utf-8"))
    prefix = [BOS_TOKEN] + inp_bytes + [SEP_TOKEN]
    sep_pos = len(prefix) - 1

    # Step decode
    step_out = step_decode(model, prefix, sep_pos, sample_n_counter,
                           max_steps=sample_n_counter * 2 + 8, device=device,
                           max_count=max_count)

    # Full-forward decode
    sentinel = (max_count + 1) if max_count is not None else model.loop_counter.sentinel
    cur = list(prefix)
    full_out = []
    for _ in range(sample_n_counter * 2 + 8):
        cv = _build_counter_array(sep_pos, len(cur), sample_n_counter,
                                  sentinel, max_count)
        x = torch.tensor([cur], dtype=torch.long, device=device)
        cv_t = torch.tensor([cv], dtype=torch.long, device=device)
        with torch.no_grad():
            logits = model(x, counter_values=cv_t)
        nxt = int(logits[0, -1].argmax().item())
        if nxt == EOS:
            break
        full_out.append(nxt)
        cur.append(nxt)

    return step_out == full_out, step_out, full_out


if __name__ == "__main__":
    from progressive_model import ProgressiveModel
    ck = torch.load("checkpoints/specialists/tower_of_hanoi_binary_eosgate_v2.pt",
                    map_location="mps", weights_only=False)
    cfg = ck["config"]; sd = ck["model"]
    lc_max = sd["loop_counter.c_emb.weight"].shape[0] - 2
    m = ProgressiveModel(d_model=cfg["d_model"], d_state=cfg["d_state"],
                         expand=2, headdim=cfg["headdim"],
                         use_loop_counter=True, loop_counter_max=lc_max)
    for _ in range(cfg["n_kernel_layers"]):
        m.add_kernel_layer()
    m.load_state_dict(sd); m.eval().to("mps")

    import time
    for n in [10, 50, 100, 200]:
        t0 = time.time()
        ok, step_out, full_out = test_step_parity(m, n, f"HANOIBIN {n}", "mps", max_count=lc_max)
        dt = time.time() - t0
        print(f"n={n}: parity={ok}, step_len={len(step_out)}, full_len={len(full_out)} ({dt:.1f}s total)")
